### ISSUE TITLE
User facing feedback when upload filesize exceeds cloudinary upload filesize

### ISSUE THREAD

**Issue by robinbeatty** [thomasvantuycom/craft-cloudinary#10]
When an asset is uploaded which exceeds Cloudinary upload filesize limit, the only feedback on the craft ui is 'A server error occurred'. Don't know how feasible it is to pass the errors back to craft but would be great to be able to tell authors why the error occurred.

**Comment by thomasvantuycom** [comment]
The plugin is unable to relay the error message thrown by the Cloudinary adapter because [the error is hardcoded](https://github.com/craftcms/flysystem/blob/db27fc34ec50239c4634533efba6fbb07c040060/src/base/FlysystemFs.php#L139) in Craft's flysystem  adapter. As a workaround, you can lower the `maxUploadFileSize` setting in Craft to match Cloudinary's size limit. This way, Craft will display an error message about the image exceeding the allowed size.
